'use client';

import { HeartHandshake, MoreHorizontal, ShieldCheck } from 'lucide-react';
import StatusPill from './StatusPill';

function MessageBubble({ message }) {
  const isCaregiver = message.role === 'caregiver';
  const initials = message.author.split(' ').slice(0, 2).map((word) => word[0]).join('');
  return <div className={`flex ${isCaregiver ? 'justify-end' : 'justify-start'}`}><div className={`flex max-w-[80%] gap-3 ${isCaregiver ? 'flex-row-reverse' : 'flex-row'}`}><span className={`mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-[10px] font-semibold ${isCaregiver ? 'bg-teal-100 text-teal-700' : 'bg-violet-100 text-violet-700'}`}>{initials}</span><div><p className={`mb-1 text-[11px] font-medium text-slate-500 ${isCaregiver ? 'text-right' : 'text-left'}`}>{message.author} <span className="text-slate-300">·</span> {message.time}</p><div className={`rounded-2xl px-4 py-3 text-sm leading-relaxed text-slate-700 ${isCaregiver ? 'rounded-tr-sm border border-teal-100 bg-teal-50' : 'rounded-tl-sm border border-violet-100 bg-violet-50'}`}>{message.text}</div></div></div></div>;
}

export default function DisputeDetail({ dispute }) {
  return <main className="flex min-w-0 flex-1 flex-col overflow-y-auto bg-white"><div className="border-b border-slate-100 px-8 pb-5 pt-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><StatusPill status={dispute.status} /><span className="text-[11px] font-semibold text-slate-400">{dispute.id}</span></div><div className="flex items-center gap-2"><button className="flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50"><HeartHandshake className="h-3.5 w-3.5" />Involve Ethics</button><button className="flex h-8 w-8 items-center justify-center rounded-lg border border-slate-200 text-slate-500 hover:bg-slate-50"><MoreHorizontal className="h-4 w-4" /></button></div></div><h2 className="mt-2 text-xl font-bold text-[#2B2E33]">{dispute.title}</h2><div className="mt-4 flex items-center gap-10 text-xs"><div><p className="font-medium uppercase tracking-wide text-slate-400">Patient</p><p className="mt-0.5 font-semibold text-[#0F6B72]">{dispute.patient}</p></div><div><p className="font-medium uppercase tracking-wide text-slate-400">Facility Location</p><p className="mt-0.5 font-semibold text-slate-700">{dispute.facility}</p></div><div><p className="font-medium uppercase tracking-wide text-slate-400">Mediator Assigned</p><p className="mt-0.5 flex items-center gap-1.5 font-semibold text-slate-700"><span className="flex h-4 w-4 items-center justify-center rounded-full bg-[#0F6B72] text-[8px] text-white">SC</span>{dispute.mediator}</p></div></div></div><div className="flex-1 px-8 py-6"><div className="mb-6 flex items-center gap-2 text-[11px] font-medium text-slate-400"><span className="h-px flex-1 bg-slate-100" /><span>Case Initiated: {dispute.caseInitiated}</span><span className="h-px flex-1 bg-slate-100" /></div>{dispute.thread.length > 0 ? <div className="space-y-6">{dispute.thread.map((message, index) => <MessageBubble key={index} message={message} />)}<div className="flex items-center justify-center gap-1.5 pt-2 text-[11px] text-slate-400"><ShieldCheck className="h-3.5 w-3.5" />Medical record verified by system</div></div> : <div className="flex h-40 items-center justify-center text-sm text-slate-400">No statements recorded for this case yet.</div>}</div></main>;
}
