import { useState } from 'react';
import { Check, Clock3, MessageCircle, Pill } from 'lucide-react';
import type { MedicationAdministration, MedicationOutcome, VisitMedication } from '@/services/visitMedications';

export default function MedicationRow({ medication, record, recordsAvailable, disabled, onAction }: { medication: VisitMedication; record?: MedicationAdministration; recordsAvailable: boolean; disabled: boolean; onAction: (status: MedicationOutcome) => void }) {
	const [failedImage, setFailedImage] = useState(false);
	const image = medication.pill_image_url && /^(https?:\/\/|\/(?!\/))/.test(medication.pill_image_url) && !failedImage ? medication.pill_image_url : null;
	return <article aria-label={medication.name} className="rounded-lg border border-[#e5e9e2] bg-[#fffefa] p-5 sm:p-6">
		<div className="flex items-start gap-4"><div className="flex size-20 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-[#e5e9e2] bg-white">{image ? <img src={image} referrerPolicy="no-referrer" alt={`${medication.name} reference pill image`} onError={() => setFailedImage(true)} className="size-full object-contain p-2" /> : <Pill aria-hidden="true" className="size-7 text-[#8ca39a]" strokeWidth={1.5} />}</div><div className="min-w-0 flex-1"><h2 className="text-lg font-bold wrap-anywhere">{medication.name}</h2><p className="mt-1 text-sm text-[#52635c]">{medication.dosage}</p><p className="mt-2 flex flex-wrap items-center gap-1.5 text-xs leading-5 text-[#287b7c]"><Clock3 aria-hidden="true" className="size-3.5" />Scheduled window: {medication.window_start_local.slice(0, 5)} - {medication.window_end_local.slice(0, 5)}</p><p className="mt-2 text-xs leading-5 text-[#737c77]">{image ? medication.pill_image_verified && medication.pill_image_source ? `Verified reference / ${medication.pill_image_source}` : 'Reference image / verification not provided' : 'Pill reference image unavailable'}</p></div></div>
		{medication.instructions && <p className="mt-4 text-sm leading-6 wrap-anywhere text-[#64716b]">{medication.instructions}</p>}
		{medication.requires_glucose_check && <p className="mt-3 text-xs font-semibold text-[#926116]">Glucose check required by recorded instructions</p>}
		<div className="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-[#e7e9e3] pt-4"><p className="text-xs leading-6 text-[#64716b]">Visit status: <span className="font-semibold capitalize">{recordsAvailable ? record?.status || 'Pending' : 'Unavailable'}</span>{record?.administered_at && <span> / {new Date(record.administered_at).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</span>}</p><div role="group" aria-label={`${medication.name} medication actions`} className="grid w-full grid-cols-3 gap-2 sm:w-auto sm:grid-cols-[120px_120px_120px]">
			<button type="button" disabled={disabled} onClick={() => onAction('administered')} className="flex min-h-12 items-center justify-center gap-1 rounded-full border border-[#637862] bg-[#637862] px-1 text-[10px] font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#637862] disabled:opacity-60 sm:text-xs"><Check aria-hidden="true" className="hidden size-3.5 sm:block" />Administered</button>
			<button type="button" disabled={disabled} onClick={() => onAction('missed')} className="min-h-12 rounded-full border border-[#c9d1cc] bg-[#f2f4f0] px-1 text-[10px] font-semibold text-[#657167] focus-visible:outline-2 focus-visible:outline-[#657167] disabled:opacity-60 sm:text-xs">Missed</button>
			<button type="button" disabled={disabled} onClick={() => onAction('refused')} className="flex min-h-12 items-center justify-center gap-1 rounded-full border border-[#d4a34d] bg-[#fffaf0] px-1 text-[10px] font-semibold text-[#94621b] focus-visible:outline-2 focus-visible:outline-[#bc8a35] disabled:opacity-60 sm:text-xs"><MessageCircle aria-hidden="true" className="hidden size-3.5 sm:block" />Refused</button>
		</div></div>
		{record?.missed_reason && <p className={`mt-3 text-sm leading-6 whitespace-pre-wrap wrap-anywhere ${record.status === 'refused' ? 'text-[#926116]' : 'text-[#64716b]'}`}><span className="font-semibold">Reason: </span>{record.missed_reason}</p>}
	</article>;
}