import { useEffect, useRef } from 'react';
import { ChevronLeft, ChevronRight, Pill, RefreshCw, X } from 'lucide-react';
import { useWeeklyMedications } from '@/hooks/useWeeklyMedications';
import { shiftWeek } from '@/services/visitMedications';

function dateKey(value: string, timezone: string) { const parts = new Intl.DateTimeFormat('en', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date(value)); return `${parts.find(part => part.type === 'year')?.value}-${parts.find(part => part.type === 'month')?.value}-${parts.find(part => part.type === 'day')?.value}`; }

export default function WeeklyMedicationCalendar({ clientId, patientName, onClose, isOnline }: { clientId: string; patientName: string; onClose: () => void; isOnline: boolean }) {
	const dialog = useRef<HTMLDialogElement>(null);
	const week = useWeeklyMedications(clientId);
	useEffect(() => { dialog.current?.showModal(); }, []);
	const days = Array.from({ length: 7 }, (_, index) => { const date = new Date(`${week.weekStart}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + index); return date.toISOString().slice(0, 10); });
	const formatter = new Intl.DateTimeFormat(undefined, { timeZone: week.data?.timezone || 'UTC', hour: 'numeric', minute: '2-digit' });
	return <dialog ref={dialog} aria-labelledby="weekly-medication-title" onCancel={event => { event.preventDefault(); onClose(); }} className="caregiver-login fixed inset-0 m-auto max-h-[92svh] w-[calc(100%-1rem)] max-w-7xl overflow-y-auto rounded-lg border border-[#d5dfd7] bg-[#fffefa] p-4 text-[#303538] backdrop:bg-black/25 sm:p-6">
		<div className="mb-5 flex items-start justify-between gap-4"><div><h2 id="weekly-medication-title" className="text-xl font-semibold">Weekly Medication Schedule</h2><p className="mt-2 text-xs text-[#737c77]">{patientName} / Read-only{week.data ? ` / ${week.data.timezone}` : ''}</p></div><button type="button" onClick={onClose} aria-label="Close weekly schedule" className="flex size-10 shrink-0 items-center justify-center rounded-lg"><X aria-hidden="true" className="size-5" /></button></div>
		<div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold">{week.weekStart} - {days[6]}</p><div className="flex gap-2"><button type="button" aria-label="Previous week" title="Previous week" disabled={!isOnline} onClick={week.previousWeek} className="flex size-11 items-center justify-center rounded-lg border border-[#d5dfd7] disabled:opacity-50"><ChevronLeft aria-hidden="true" className="size-4" /></button><button type="button" aria-label="Next week" title="Next week" disabled={!isOnline} onClick={week.nextWeek} className="flex size-11 items-center justify-center rounded-lg border border-[#d5dfd7] disabled:opacity-50"><ChevronRight aria-hidden="true" className="size-4" /></button><button type="button" aria-label="Refresh weekly schedule" title="Refresh weekly schedule" disabled={!isOnline || week.loading} onClick={week.refresh} className="flex size-11 items-center justify-center rounded-lg disabled:opacity-50"><RefreshCw aria-hidden="true" className="size-4" /></button></div></div>
		{week.loading ? <p role="status" className="py-8 text-sm text-[#737c77]">Loading weekly dose records...</p> : week.error ? <p role="alert" className="py-8 text-sm leading-6 text-[#79523e]">{week.error}</p> : week.data && <div className="overflow-x-auto"><div role="region" aria-label="Read-only weekly medication calendar" className="grid min-w-280 grid-cols-7 gap-3">{days.map(day => <section key={day} aria-label={day} className="min-w-0 rounded-lg border border-[#e5e9e2] bg-white p-3"><h3 className="mb-4 border-b border-[#edf0eb] pb-3 text-xs font-semibold">{new Intl.DateTimeFormat(undefined, { timeZone: 'UTC', weekday: 'short', month: 'short', day: 'numeric' }).format(new Date(`${day}T12:00:00Z`))}</h3><div className="space-y-3">{week.data!.doses.filter(dose => dateKey(dose.scheduled_at, week.data!.timezone) === day).sort((first, second) => Date.parse(first.scheduled_at) - Date.parse(second.scheduled_at)).map(dose => {
			const hasAdministration = dose.status === 'administered' && Boolean(dose.administered_at);
			const actual = dose.administered_at ? Date.parse(dose.administered_at) : null;
			const timing = hasAdministration && actual !== null ? actual < Date.parse(dose.window_start) ? 'Before window' : actual > Date.parse(dose.window_end) ? 'After window' : 'Within window' : dose.status === 'administered' ? 'Time unavailable' : null;
			const style = dose.status === 'refused' ? 'bg-[#fff1d5] text-[#926116]' : dose.status === 'missed' ? 'bg-[#fbe9e6] text-[#9b4238]' : timing === 'Within window' ? 'bg-[#e6f0e7] text-[#49694d]' : dose.status === 'administered' ? 'bg-[#fff1d5] text-[#926116]' : 'bg-[#eef1ef] text-[#657269]';
			return <article key={dose.id} className="rounded-lg border border-[#e9eee8] p-3"><h4 className="flex items-start gap-1.5 text-xs font-bold wrap-anywhere"><Pill aria-hidden="true" className="mt-0.5 size-3 shrink-0 text-[#5a9d99]" />{dose.medication_name}</h4><p className="mt-1 text-[11px] leading-5 wrap-anywhere text-[#737c77]">{dose.dosage}</p><p className="mt-2 text-[11px] text-[#52635c]">Due {formatter.format(new Date(dose.scheduled_at))}</p><p className="mt-1 text-[10px] text-[#737c77]">Window {formatter.format(new Date(dose.window_start))} - {formatter.format(new Date(dose.window_end))}</p><span className={`mt-2 inline-flex rounded-full px-2 py-1 text-[10px] font-semibold capitalize ${style}`}>{dose.status === 'unrecorded' ? 'No record' : dose.status}</span>{timing && <p className="mt-2 text-[11px] font-semibold text-[#52635c]">{timing}{dose.administered_at ? ` / ${formatter.format(new Date(dose.administered_at))}` : ''}</p>}{dose.reason && <p className="mt-2 text-[11px] leading-5 whitespace-pre-wrap wrap-anywhere text-[#737c77]">Reason: {dose.reason}</p>}{dose.recorded_by_name && <p className="mt-2 text-[10px] text-[#737c77]">{dose.recorded_by_name}</p>}</article>;
		})}{!week.data!.doses.some(dose => dateKey(dose.scheduled_at, week.data!.timezone) === day) && <p className="text-xs leading-6 text-[#737c77]">No scheduled doses returned.</p>}</div></section>)}</div></div>}
	</dialog>;
}