apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Uses the Docker container name and internal port defined in Docker Compose
    url: http://prometheus:9090
    isDefault: true
    editable: false