import { CheckCircle2, ClipboardList, Clock3, MoreVertical, Pencil, SkipForward, Trash2 } from 'lucide-react';
import type { VisitTask } from '@/services/visitTasks';
import type { TaskAction } from '@/hooks/useVisitTasks';

export default function VisitTaskCard({ task, disabled, onAction }: { task: VisitTask; disabled: boolean; onAction: (action: TaskAction) => void }) {
	return <article aria-label={task.title} className="rounded-lg border border-[#e7e9e3] bg-[#fffefa] p-5 sm:p-6">
		<div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3"><span aria-hidden="true" className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-[#eaf3f0] text-[#5a9d99]"><ClipboardList className="size-5" /></span><div className="min-w-0"><h2 className="text-base leading-6 font-bold wrap-anywhere">{task.title}</h2><div className="mt-2 flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold capitalize ${task.priority === 'high' ? 'bg-[#fbe9e6] text-[#9b4238]' : task.priority === 'normal' ? 'bg-[#edf3f6] text-[#526f83]' : 'bg-[#eef2ec] text-[#657167]'}`}>{task.priority} priority</span><span className={`rounded-full px-2 py-1 text-[10px] font-semibold capitalize ${task.status === 'completed' ? 'bg-[#e6f0e7] text-[#49694d]' : task.status === 'skipped' ? 'bg-[#fff1d5] text-[#926116]' : 'bg-[#eceeeb] text-[#657167]'}`}>{task.status}</span></div></div></div>
			<details className="relative shrink-0"><summary aria-label={`${task.title} more actions`} title={`${task.title} more actions`} className="flex size-10 cursor-pointer list-none items-center justify-center rounded-lg text-[#64716b] hover:bg-[#edf2ed] focus-visible:outline-2 focus-visible:outline-[#287b7c] [&::-webkit-details-marker]:hidden"><MoreVertical aria-hidden="true" className="size-5" /></summary><div className="absolute top-11 right-0 z-20 w-48 rounded-lg border border-[#d7e1d8] bg-white p-1 shadow-lg"><button type="button" disabled={disabled} onClick={event => { event.currentTarget.closest('details')?.removeAttribute('open'); onAction({ kind: 'delete', task }); }} className="flex min-h-11 w-full items-center gap-2 rounded px-3 text-left text-xs font-semibold text-[#9b4238] hover:bg-[#fff5f1] focus-visible:outline-2 focus-visible:outline-[#9b4238] disabled:opacity-50"><Trash2 aria-hidden="true" className="size-4" />Delete entry</button></div></details>
		</div>
		{task.details && <p className="mt-4 text-sm leading-6 whitespace-pre-wrap wrap-anywhere text-[#64716b]">{task.details}</p>}
		<p className="mt-4 flex items-center gap-2 text-xs leading-5 text-[#737c77]"><Clock3 aria-hidden="true" className="size-3.5 shrink-0" />{task.due_at ? `Due ${new Date(task.due_at).toLocaleString()}` : 'Time not specified'}</p>
		{task.skip_reason && <p className="mt-3 text-sm leading-6 whitespace-pre-wrap wrap-anywhere text-[#926116]"><span className="font-semibold">Skip reason: </span>{task.skip_reason}</p>}
		{task.completed_at && <p className="mt-3 text-xs text-[#64716b]">Completed {new Date(task.completed_at).toLocaleString()}</p>}
		<div role="group" aria-label={`${task.title} task actions`} className="mt-5 grid grid-cols-3 gap-2 border-t border-[#e7e9e3] pt-4 sm:ml-auto sm:w-96">
			<button type="button" disabled={disabled || task.status !== 'pending'} onClick={() => onAction({ kind: 'complete', task })} className="flex min-h-12 items-center justify-center gap-1.5 rounded-full border border-[#637862] bg-[#637862] px-1 text-xs font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#637862] disabled:opacity-60"><CheckCircle2 aria-hidden="true" className="hidden size-3.5 sm:block" />Complete</button>
			<button type="button" disabled={disabled || task.status !== 'pending'} onClick={() => onAction({ kind: 'skip', task })} className="flex min-h-12 items-center justify-center gap-1.5 rounded-full border border-[#d4a34d] bg-[#fffaf0] px-1 text-xs font-semibold text-[#94621b] focus-visible:outline-2 focus-visible:outline-[#bc8a35] disabled:opacity-60"><SkipForward aria-hidden="true" className="hidden size-3.5 sm:block" />Skip</button>
			<button type="button" disabled={disabled} onClick={() => onAction({ kind: 'edit', task })} className="flex min-h-12 items-center justify-center gap-1.5 rounded-full border border-[#cdd3d0] bg-[#f6f7f5] px-1 text-xs font-semibold text-[#68736c] focus-visible:outline-2 focus-visible:outline-[#68736c] disabled:opacity-60"><Pencil aria-hidden="true" className="hidden size-3.5 sm:block" />Edit</button>
		</div>
	</article>;
}