'use client';

import { useState } from 'react';
import { CheckCircle2, MoreHorizontal } from 'lucide-react';
import { RECORDS, STATUS_STYLES } from './reportData';

export default function ReportTable() {
  const [page, setPage] = useState(1);
  return <div className="mt-6 rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-bold text-[#2B2E33]">Resource Utilization Log</h2><p className="text-xs text-slate-400">Precision archival data for regulatory compliance and audit readiness.</p></div><button className="flex h-7 w-7 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-50"><MoreHorizontal className="h-4 w-4" /></button></div><div className="overflow-x-auto"><table className="w-full border-collapse text-sm"><thead><tr className="text-left text-[10px] font-semibold uppercase tracking-wide text-slate-400"><th className="px-5 py-2.5">Record ID</th><th className="px-5 py-2.5">Facility / Location</th><th className="px-5 py-2.5">Personnel Category</th><th className="px-5 py-2.5">Status</th><th className="px-5 py-2.5 text-right">Utility Ratio</th><th className="px-5 py-2.5 text-right">Logged Capacity</th><th className="px-5 py-2.5 text-right">Timestamp</th></tr></thead><tbody>{RECORDS.map((record, index) => <tr key={record.id} className={index % 2 === 1 ? 'bg-slate-50/60' : 'bg-white'}><td className="px-5 py-3 font-mono text-xs text-slate-500">{record.id}</td><td className="px-5 py-3 font-semibold text-slate-700">{record.facility}</td><td className="px-5 py-3 text-slate-500">{record.category}</td><td className="px-5 py-3"><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${STATUS_STYLES[record.status]}`}>{record.status}</span></td><td className="px-5 py-3 text-right font-mono font-semibold text-[#0F6B72]">{record.ratio}</td><td className="px-5 py-3 text-right font-mono text-slate-600">{record.hours}</td><td className="px-5 py-3 text-right font-mono text-xs text-slate-400">{record.timestamp}</td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 px-5 py-3"><span className="flex items-center gap-1.5 text-[11px] text-slate-400"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" />All visible records verified against clinical database</span><div className="flex items-center gap-1.5"><button onClick={() => setPage((value) => Math.max(1, value - 1))} className="rounded-md px-2.5 py-1 text-xs font-medium text-slate-400 hover:bg-slate-50">Previous</button>{[1, 2, 3].map((number) => <button key={number} onClick={() => setPage(number)} className={`h-6 w-6 rounded-md text-xs font-semibold ${page === number ? 'bg-[#1B2733] text-white' : 'text-slate-500 hover:bg-slate-50'}`}>{number}</button>)}<button onClick={() => setPage((value) => Math.min(3, value + 1))} className="rounded-md px-2.5 py-1 text-xs font-medium text-slate-500 hover:bg-slate-50">Next</button></div></div></div>;
}
