'use client';

import { ChevronDown, FileText, Info, Search } from 'lucide-react';

const DIAGNOSES = ['General Geriatric', 'Dementia', "Parkinson's", 'Post-Stroke', 'Other'];

export default function DiagnosisDetails({ diagnosis, onDiagnosisChange, notes, onNotesChange }) {
  const isGeriatric = diagnosis === 'General Geriatric';

  return (
    <div className="space-y-6">
      <section className="rounded-xl border border-slate-200/80 bg-white p-5 shadow-[0_3px_14px_-8px_rgba(15,23,42,0.16)]">
        <div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-md bg-teal-50 text-[#0F6B72]"><FileText className="h-3.5 w-3.5" /></span><h2 className="text-sm font-bold text-[#2B2E33]">Primary Admission Reason</h2></div>
        <label className="mt-6 block"><span className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Clinical Diagnosis</span><span className="relative mt-2 block"><select value={diagnosis} onChange={(event) => onDiagnosisChange(event.target.value)} className="w-full appearance-none rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm font-medium text-slate-700 outline-none transition-colors focus:border-[#0F6B72] focus:ring-2 focus:ring-[#0F6B72]/15">{DIAGNOSES.map((item) => <option key={item}>{item}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /></span></label>
        {isGeriatric && <div className="mt-4 flex overflow-hidden rounded-xl bg-[#ECF8FA]"><div className="flex w-1/2 gap-3 p-5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#D6F0F2] text-[#0F6B72]"><Info className="h-4 w-4" /></span><div><p className="text-xs font-bold text-[#24535A]">Geriatric Care Protocol Active</p><p className="mt-2 text-[11px] leading-relaxed text-slate-600">Selecting General Geriatric enables specialized screening for mobility, polypharmacy, and social determinants of health specific to senior populations.</p><div className="mt-3 flex gap-3 text-[9px] font-semibold uppercase tracking-wide text-[#0F6B72]"><span>◉ Mobility Screen</span><span>◉ Cognitive Baseline</span></div></div></div><div className="relative hidden min-h-40 w-1/2 bg-[linear-gradient(135deg,#d7eef0,#f2b2a7)] sm:block"><div className="absolute bottom-0 left-[48%] h-28 w-12 rounded-t-[45%] bg-[#4e6f6e]" /><div className="absolute bottom-0 left-[35%] h-16 w-20 rounded-t-[55%] bg-[#67534a]" /><div className="absolute bottom-20 left-[44%] h-9 w-9 rounded-full bg-[#b87961]" /><div className="absolute bottom-9 left-[31%] h-7 w-7 rounded-full bg-[#a87461]" /></div></div>}
      </section>
      <div className="flex items-start gap-3 px-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-400"><FileText className="h-3.5 w-3.5" /></span><div className="flex-1"><div className="flex items-center gap-2"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Clinical Description</p><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[9px] font-medium text-slate-400">ICD-10 · Z00.00</span></div><p className="mt-1 text-[11px] italic text-slate-500">Encounter for general adult medical examination without abnormal findings in elderly patients.</p></div></div>
      <section className="border-t border-slate-200 pt-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-md bg-sky-50 text-[#0F6B72]"><Search className="h-3.5 w-3.5" /></span><h2 className="text-sm font-bold text-[#2B2E33]">Secondary History &amp; Notes</h2></div><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium text-slate-500">Optional</span></div><label className="mt-5 block"><span className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Assessment Observations</span><textarea value={notes} onChange={(event) => onNotesChange(event.target.value)} rows={4} placeholder="Enter relevant medical history, comorbidities, or specific patient concerns during intake..." className="mt-2 w-full resize-none rounded-lg border border-slate-300 bg-white px-3 py-3 text-sm text-slate-700 placeholder:text-slate-400 outline-none focus:border-[#0F6B72] focus:ring-2 focus:ring-[#0F6B72]/15" /></label><p className="mt-2 text-[10px] text-slate-400">ⓘ Notes are encrypted and synced to the Patient Portal.</p></section>
    </div>
  );
}
